-- Copyright (c) 2026 EZBillify Ventures Pvt Ltd. All rights reserved.
-- Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
-- 
-- WARNING & LIABILITY DISCLAIMER:
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-- AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-- IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
-- FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
-- DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-- SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
-- CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-- 
-- IMPORTANT: WHOEVER COPIES, REDISTRIBUTES, OR USES THIS SOFTWARE MUST KNOW THAT
-- UNDER NO CIRCUMSTANCES CAN THEY RECOVER DAMAGES, LOSSES, OR LIABILITIES
-- ENCOUNTERED FROM THE USE, MODIFICATION, OR DISTRIBUTION OF THIS SOFTWARE.

-- Migration 001: Add Employment and Salary Structure to Employees

-- 1. Create Enums for new domains
DO $$ BEGIN
    CREATE TYPE employment_type AS ENUM ('full_time', 'part_time', 'internship');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE salary_type AS ENUM ('fixed_monthly', 'hourly', 'daily', 'stipend');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- 2. Add columns to `employees` table natively
ALTER TABLE employees
ADD COLUMN IF NOT EXISTS employment_type employment_type NOT NULL DEFAULT 'full_time',
ADD COLUMN IF NOT EXISTS salary_structure salary_type NOT NULL DEFAULT 'fixed_monthly',
ADD COLUMN IF NOT EXISTS base_salary NUMERIC(15,2) NOT NULL DEFAULT 0;

-- 3. Optionally update existing users backward compatibly (Assuming existing are full_time)
UPDATE employees
SET employment_type = 'full_time',
    salary_structure = 'fixed_monthly'
WHERE employment_type IS NULL OR salary_structure IS NULL;
