-- Copyright (c) 2026 EZBillify Ventures Pvt Ltd. All rights reserved.
-- Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
-- 
-- WARNING & LIABILITY DISCLAIMER:
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-- AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-- IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
-- FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
-- DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-- SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
-- CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-- 
-- IMPORTANT: WHOEVER COPIES, REDISTRIBUTES, OR USES THIS SOFTWARE MUST KNOW THAT
-- UNDER NO CIRCUMSTANCES CAN THEY RECOVER DAMAGES, LOSSES, OR LIABILITIES
-- ENCOUNTERED FROM THE USE, MODIFICATION, OR DISTRIBUTION OF THIS SOFTWARE.

-- 1. Extend System Configuration for Root Node Identity
ALTER TABLE system_config ADD COLUMN IF NOT EXISTS company_name TEXT DEFAULT 'Namaah Tech';
ALTER TABLE system_config ADD COLUMN IF NOT EXISTS founder_name TEXT DEFAULT 'Aryan';
ALTER TABLE system_config ADD COLUMN IF NOT EXISTS founder_designation TEXT DEFAULT 'Chief Executive Officer';

-- 2. Restructure Teams for Recursive Department/Team Hierarchy
-- This enables "Main Department" -> "Sub-Team" nesting logic.
ALTER TABLE teams ADD COLUMN IF NOT EXISTS type TEXT CHECK (type IN ('department', 'team')) NOT NULL DEFAULT 'team';
ALTER TABLE teams ADD COLUMN IF NOT EXISTS parent_id UUID REFERENCES teams(id) ON DELETE CASCADE;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS head_designation TEXT;

-- 3. Ensure RLS allows inserts (assuming super_admin or authenticated for now)
-- Adjust based on your actual auth requirements.
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON "public"."teams"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON "public"."teams"
AS PERMISSIVE FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Enable update for authenticated users only" ON "public"."teams"
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (true);

-- 4. Similar policies for system_config
ALTER TABLE system_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read for config" ON "public"."system_config"
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable update for config" ON "public"."system_config"
AS PERMISSIVE FOR UPDATE
TO authenticated
USING (true);
