-- Copyright (c) 2026 EZBillify Ventures Pvt Ltd. All rights reserved.
-- Licensed under the GNU Affero General Public License v3.0 (AGPL-3.0).
-- 
-- WARNING & LIABILITY DISCLAIMER:
-- THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
-- AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
-- IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
-- DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
-- FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
-- DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
-- SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
-- CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
-- OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
-- OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-- 
-- IMPORTANT: WHOEVER COPIES, REDISTRIBUTES, OR USES THIS SOFTWARE MUST KNOW THAT
-- UNDER NO CIRCUMSTANCES CAN THEY RECOVER DAMAGES, LOSSES, OR LIABILITIES
-- ENCOUNTERED FROM THE USE, MODIFICATION, OR DISTRIBUTION OF THIS SOFTWARE.

-- ============================================================================
-- 00000000_baseline.sql
--
-- THIS FILE IS A PLACEHOLDER.
--
-- Replace its contents with a `pg_dump --schema-only --no-owner --no-acl` of
-- the CURRENT production Supabase project before deploying to a new project.
--
-- The old 97 layered migrations at src/supabase/migrations/ accumulated mutual
-- dependencies, duplicate file numbers, role enum DROP+recreate cycles, and
-- hardcoded seed data that prevent a clean replay on a fresh DB. The clean
-- solution is to capture the current SCHEMA STATE as a single baseline and
-- treat that as migration zero.
--
-- ─── How to generate this file ──────────────────────────────────────────────
--
-- 1. Get the database URL from the CURRENT (old) Supabase project:
--      Settings → Database → Connection string → URI (use the direct connection,
--      not the pooler). It looks like:
--        postgres://postgres.<ref>:<password>@aws-0-...pooler.supabase.com:5432/postgres
--
-- 2. Run pg_dump locally (requires postgres client tools — `brew install libpq` on Mac):
--      pg_dump \
--        --schema-only \
--        --no-owner \
--        --no-acl \
--        --schema=public \
--        --schema=storage \
--        "<DATABASE_URL>" \
--        > supabase/migrations/00000000_baseline.sql
--
-- 3. Manually clean the dump:
--      - Remove `CREATE EXTENSION` lines that target system schemas Supabase
--        already manages (extensions, auth, pgsodium).
--      - Remove any `SET` statements at the top that reference roles that
--        don't exist on the new project.
--      - Keep all CREATE TABLE / CREATE TYPE / CREATE FUNCTION / CREATE TRIGGER
--        / CREATE INDEX / CREATE POLICY statements in public schema.
--
-- 4. Verify on a fresh local Supabase:
--      npx supabase stop && npx supabase start
--      npx supabase db reset    # runs all migrations from scratch
--      # If it errors, fix the dump and retry.
--
-- 5. Once green locally, you're ready to `supabase db push` to the new project.
--
-- ─── What goes on top of this baseline ──────────────────────────────────────
--
-- After this file replays the current schema, `00000001_role_model.sql` runs
-- next. That migration:
--   - Adds 'hr' and 'accounts' to the user_role enum (if not present)
--   - Adds is_dept_lead, is_team_lead, managed_department_id, managed_team_id
--     columns to employees
--   - Migrates existing 'dept_lead'/'team_lead' users → 'employee' with flags
--   - Creates employee_permissions table for per-user overrides
--   - Creates effective_permissions view
--
-- It is idempotent and safe to re-run.
--
-- ─── Until you generate the real dump ───────────────────────────────────────
--
-- This placeholder is intentionally non-executable so you don't accidentally
-- deploy an empty schema. Replace the SELECT below with the actual dump.
-- ============================================================================

-- Baseline placeholder is a no-op since remote schema is already initialized.
SELECT 1;
